"""Bake `prompts/` and the sample list into a Python module for the Worker.

Pyodide has no filesystem to walk and no PyYAML in the bundle, so the frontmatter
is parsed here, at build time, and written out as plain Python literals. The
markdown files stay canonical - this is derived, regenerated by `make bundle`,
and gitignored.

    python3 tools/build_bundle.py
"""

from __future__ import annotations

import pprint
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "backend" / "src"))

from collaborate import prompts  # noqa: E402

OUT = REPO_ROOT / "backend" / "src" / "collaborate" / "bundle.py"

HEADER = '''"""Generated by `make bundle` - do not edit.

The Worker's only source of prompts: `prompts/<id>/v<version>.md` parsed at
build time, since Pyodide has neither the files nor PyYAML.
"""

# fmt: off
'''


def main() -> int:
    found = {}
    for path in sorted((REPO_ROOT / "prompts").glob("*/v*.md")):
        prompt = prompts.parse(path.read_text(encoding="utf-8"), source=str(path))
        found[(prompt.id, prompt.version)] = {
            "id": prompt.id,
            "version": prompt.version,
            "title": prompt.title,
            "status": prompt.status,
            "body": prompt.body,
            "defaults": prompt.defaults,
        }
    if not found:
        print("no prompts found under prompts/", file=sys.stderr)
        return 1

    samples = sorted(p.stem for p in (REPO_ROOT / "samples").glob("*.svg"))

    text = HEADER
    text += f"\nPROMPTS = {pprint.pformat(found, width=88, sort_dicts=True)}\n"
    text += f"\nSAMPLES = {pprint.pformat(samples, width=88)}\n"
    OUT.write_text(text, encoding="utf-8")

    for (pid, version), entry in found.items():
        print(f"  {pid} v{version}  {len(entry['body']):>6} chars  {entry['title']}")
    print(f"  samples: {', '.join(samples) or 'none'}")
    print(f"-> {OUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
